# Generated by Django 3.2.5 on 2021-07-02 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='benificial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_registration', models.DateTimeField()),
                ('contact_1', models.IntegerField(default=0)),
                ('contact_2', models.IntegerField(default=0)),
                ('is_registered', models.BooleanField(default=False)),
                ('dose_num', models.IntegerField(default=1)),
                ('vaccine_type', models.CharField(default='', max_length=100)),
                ('is_delivered', models.BooleanField(default=False)),
                ('slot_timing', models.DateTimeField()),
                ('is_vaccinated', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
