# Generated by Django 3.2.5 on 2021-07-02 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='benificial',
            name='slot_timing',
        ),
        migrations.AddField(
            model_name='benificial',
            name='slot_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='benificial',
            name='slot_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='benificial',
            name='time_of_registration',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='benificial',
            name='date_of_registration',
            field=models.DateField(null=True),
        ),
    ]
