# Generated by Django 3.2.5 on 2021-07-02 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20210702_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='benificial',
            name='date_of_registration',
        ),
        migrations.RemoveField(
            model_name='benificial',
            name='slot_date',
        ),
        migrations.RemoveField(
            model_name='benificial',
            name='slot_time',
        ),
        migrations.RemoveField(
            model_name='benificial',
            name='time_of_registration',
        ),
        migrations.AddField(
            model_name='benificial',
            name='registration_timing',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='benificial',
            name='roll_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='benificial',
            name='slot_timing',
            field=models.DateTimeField(null=True),
        ),
    ]
